# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Note.create({ number: 1, name: 'C3'})
Note.create({ number: 2, name: 'C#3'})
Note.create({ number: 3, name: 'D3'})
Note.create({ number: 4, name: 'D#3'})
Note.create({ number: 5, name: 'E3'})
Note.create({ number: 6, name: 'F3'})
Note.create({ number: 7, name: 'F#3'})
Note.create({ number: 8, name: 'G3'})
Note.create({ number: 9, name: 'G#3'})
Note.create({ number: 10, name: 'A3'})
Note.create({ number: 11, name: 'A#3'})
Note.create({ number: 12, name: 'B'})
Note.create({ number: 13, name: 'C4'})
Note.create({ number: 14, name: 'C#4'})
Note.create({ number: 15, name: 'D4'})
Note.create({ number: 16, name: 'D#4'})
Note.create({ number: 17, name: 'E4'})
Note.create({ number: 18, name: 'F4'})
Note.create({ number: 19, name: 'F#4'})
Note.create({ number: 20, name: 'G4'})
Note.create({ number: 21, name: 'G#4'})
Note.create({ number: 22, name: 'A4'})
Note.create({ number: 23, name: 'A#4'})
Note.create({ number: 24, name: 'B4'})
